/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    // 'orientation-training/intro',
    'orientation-training/index',
    'orientation-training/step-1',
    'orientation-training/step-2',
    'orientation-training/step-3',
    'orientation-training/step-4',
  ],
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '行政事務',
      link: {type: 'doc', id: 'administrative-affairs/index'},
      items: [
        'administrative-affairs/intro',
        'administrative-affairs/general-reimburse-instructions',
        'administrative-affairs/10k',
        'administrative-affairs/equipment-costs',
        'administrative-affairs/most-expenditure',
        'administrative-affairs/lecturer',
        'administrative-affairs/tender',
        'administrative-affairs/transfer',
        'administrative-affairs/travel-expenses',
        'administrative-affairs/employment',
        'administrative-affairs/GoAbroad',
      ],
    },
    {
      type: 'category',
      label: '軟體工程與程式素養',
      link: {type: 'doc', id: 'software-engineering/index'},
      items: [
        'software-engineering/coding-style',
        'software-engineering/solid',
        'software-engineering/uml',
        'software-engineering/xp-simplicity-rules',
        'software-engineering/design-pattern',
        'software-engineering/unit-testing',
        'software-engineering/three-virtues',
        'software-engineering/clean-code',
        'software-engineering/favor-composition',
        'software-engineering/version',
      ],
    },
    'csharp',
    {
      type: 'category',
      label: '工具',
      link: {type: 'doc', id: 'tools/index'},
      items: [
        'tools/git',
        'tools/github',
        'tools/workflow',
        'tools/visual-studio',
        'tools/3d-printer',
      ],
    },
    {
      type: 'category',
      label: 'HIWIN',
      link: {type: 'doc', id: 'hiwin/index'},
      items: [
        'hiwin/tutorial',
        'hiwin/14th',
        'hiwin/13th',
      ],
    },
    'member-rules',
  ]
};

module.exports = sidebars;
